spring:
  r2dbc:
    url: r2dbc:h2:mem:///~/db/benoggl
    username: sa
    password:
  rsocket:
    server:
      port: 7000
      mapping-path: /rsocket
      transport: websocket
  sql:
    init:
      mode: always