spring:
  datasource:
    url: jdbc:h2:mem:;DB_CLOSE_DELAY=-1;USER=sa;PASSWORD=sa
    username: sa
    password: sa
    schema: classpath:init_schema.sql
  main:
    lazy-initialization: true
  rsocket:
    server:
      port: 7000
      mapping-path: /rsocket
      transport: websocket
  sql:
    init:
      mode: always